capstone_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('emails.urls')),
    path('captcha/', include('captcha.urls')),
]

emails/urls.py
from django.urls import path
from .views import ContactForm, ContactThankYou



app_name = 'emails'

urlpatterns = [

     path('contact/', ContactForm.as_view(), name='contact_page'),
     path('contact/thank_you/', ContactThankYou.as_view(), name = 'contact_thank_you')

]

my_blog/urls.py
from django.urls import path
from .views import (HomeTemplateView, PostCreate, PostDetailView, PostListView, 
                    DraftListView, HomeRedirectView, SearchResultsView, 
                    UpdatePostView, DeletePost, PostView)
from django.conf.urls.static import static
from django.conf import settings

app_name = 'my_blog' #important for the project to specify app names. Easy reference for use in views and html


urlpatterns = [

    path('home/', HomeTemplateView.as_view(), name = 'home'),
    path('',HomeRedirectView.as_view(), name='home_redirect'),
    path('create/', PostCreate.as_view(), name = 'create_post'),
    path('post_list/', PostListView.as_view(), name = 'post_list'),
    path('draft_list/', DraftListView.as_view(), name = 'draft_list'),
    path('search/', SearchResultsView.as_view(), name = 'search_results'),
    path('post_detail/<int:pk>/', PostView.as_view(), name = 'post_detail'),
    path('update_post/<int:pk>/', UpdatePostView.as_view(), name = 'update_post'),
    path('delete_post/<int:pk>/', DeletePost.as_view(), name = 'delete_post'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

"""+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) is ONLY for development
it helps create the file on the specified path (defined in settings.py and model's post_image field) on upload, and
it helps GET the post thumbnails when they are already uploaded by user, for 
rendering in the post list template"""

my_blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField

# Create your models here.

#Database table for all the posts. If draft==True then the post is considered a DRAFT.
#drafts are handled differently, as they require admin privileges to view
class Post(models.Model):
    author_f_name = models.CharField(max_length = 30, verbose_name = 'First Name')
    author_l_name = models.CharField(max_length = 30, verbose_name='Last Name')
    author_email = models.EmailField()
    creation_date = models.DateTimeField(default = timezone.now, verbose_name = 'Time of creation')
    publication_date = models.DateTimeField(blank = True, null = True)
    post_title = models.CharField(max_length = 600, verbose_name = 'Title')
    draft = models.BooleanField(default = True, verbose_name= 'Is this a Draft?(check the box if YES)')
    post_image = models.ImageField( upload_to = "thumbnails/", height_field = None, width_field = None, max_length=100, blank = True, null = True, verbose_name = 'Post Thumbnail')
    post_main = RichTextField(blank = True, null = True, max_length = None,verbose_name = "")
    

    #this will be a button to publish a post out of a list of draft posts, or the current one
    def publish_post(self):
        if self.draft == True :
            self.draft = False
            self.publication_date = timezone.now
            self.save()
        
    #this will be the button to save a post to a list of draft posts, without publishing
    #the posts will be displayed in two different pages, depending if they are drafts of not
    #this will happen in the views section

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)


    def __str__(self):
        return self.post_title


#-----------------------------------------------------------------
#-----------------------------------------------------------------
#-----------------------------------------------------------------


#database table for comments. commenters just provide their info and can add a comment.
#no special handling needed, but we store the comments. SIDENOTE: apply analytics later on.
class Comment(models.Model):
    post = models.ForeignKey('my_blog.Post',on_delete=models.CASCADE, related_name='comments')
    comment_title = models.CharField(max_length=600, verbose_name='Title')
    nickname = models.CharField(max_length=100, verbose_name='UserName')
    comment_content = models.TextField(max_length=None, verbose_name='Leave a Comment...')
    create_date = models.DateTimeField(default = timezone.now)
    approved_comment = models.BooleanField(default=False)


    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.comment_content



#-----------------------------------------------------------------
#-----------------------------------------------------------------
#-----------------------------------------------------------------

my_blog/forms.py
from cProfile import label
from xml.sax.xmlreader import AttributesImpl
from django import forms
from.models import Post, Comment
from django.forms import ModelForm



class PostForm(ModelForm):

    #make the post_image field required in posts and drafts.
    #this way, there cant be an error from missing url
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['post_image'].required = True    
    
    class Meta:
        model = Post
        fields = '__all__'
        
        widgets = {
            'author_f_name' : forms.TextInput(attrs={'class':'form-control',
                                                        'id':'floatingInput',
                                                        'placeholder':'Name Here'}),

            'author_l_name' : forms.TextInput(attrs={'class':'form-control',
                                                        'id':'floatingInput',
                                                        'placeholder':'Last Name Here'}),

            'author_email' : forms.EmailInput(attrs={'class':'form-control',
                                                        'id':'floatingInput',
                                                        'placeholder':'email here'}),

            'creation_date' : forms.DateTimeInput(attrs={'class':'form-control'}),

            'publication_date' : forms.DateTimeInput(attrs={'class':'form-control'}),

            'post_title' : forms.TextInput(attrs={'class':'form-control',
                                                        'id':'floatingInput',
                                                        'placeholder':'Title Here'}),

            'post_main' : forms.Textarea(attrs={'class':'form-control',
                                                        'id':'floatingTextarea',
                                                        'placeholder':'Post Here'}),

            'post_image' : forms.ClearableFileInput(attrs={'class':'form-control'})
        }

################################################################################################
################################################################################################
################################################################################################

class CommentModelForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['nickname', 'comment_title', 'comment_content']

        widgets = {

            'nickname': forms.TextInput(attrs={'class':'form-control',
                                                        'id':'floatingInput',
                                                        'placeholder':'Nickname Here'}),


            'comment_title' : forms.TextInput(attrs={'class':'form-control',
                                                        'id':'floatingInput',
                                                        'placeholder':'Title Here'}),

            'comment_content' : forms.Textarea(attrs={'class':'form-control',
                                                        'id':'floatingTextarea',
                                                        'placeholder':'Comment Here',
                                                        'style':'height:15%;'}),

        }

my_blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
################################################################
from emails.models import Subscriber
from .models import Post, Comment
################################################################
from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.edit import CreateView, FormView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm, CommentModelForm
from emails.forms import SubscriberForm
################################################################
from django.db.models import Q
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic.detail import SingleObjectMixin
################################################################

# Create your views here.

# homepage related views

#make the homepage a CreateView in order to render subscriber form and SAVE the subscriber  AND send email.
class HomeTemplateView(CreateView):
    model = Subscriber
    form_class = SubscriberForm
    success_url = reverse_lazy('my_blog:home')

    #the template thats going to be used is the homepage template
    def get_template_names(self):
        return ['my_blog/home.html']

    #enable use of {{subscriber_form}} in html instead of default {{form}}
    def get_context_data(self, **kwargs):
        context = super(HomeTemplateView, self).get_context_data(**kwargs)
        context['subscriber_form'] = context['form']
        return context

    #need this method in order to send a subscription email.
    def form_valid(self, form):

        #initialize important email values
        instance_name = form.cleaned_data.get('f_name') #GET the instance first name
        instance_email = form.cleaned_data.get('email') #GET the instance email
        sbj = 'My blog Newsletter Subscription'
        msg = f'Thank you for subscribing {str.capitalize(instance_name)}. You are now going to get an email notifying you whenever there is a new post!'

        #send the mail through this function
        send_mail(
            subject= sbj,
            message = msg,
            from_email= settings.EMAIL_HOST_USER, # look at seetings for email configurations, .env file(same dir as settings file) and environ needed
            recipient_list= [instance_email],
            fail_silently= False
        )
        return super(HomeTemplateView, self).form_valid(form)




class HomeRedirectView(RedirectView): #this redirects from www.ex.com/ to www.ex.com/home/ . look at app urls
    url= 'home/'

#-----------------------------------------------------------------
#-----------------------------------------------------------------
#-----------------------------------------------------------------

#post/draft related views

class PostCreate(LoginRequiredMixin,CreateView):
    form_class = PostForm
    success_url = reverse_lazy('my_blog:home')
    template_name = 'my_blog/Post_form.html'
    #space for method to send mass emails to subscribers
    #when a new post is created

class PostListView(ListView):
    model = Post
    context_object_name = 'post_list'
    queryset = Post.objects.filter(draft = False)

class UpdatePostView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'my_blog/update_post.html'
    success_url = reverse_lazy('my_blog:post_list')


class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'my_blog/delete_post_confirm.html'
    success_url = reverse_lazy('my_blog:post_list')

########################################################################

"""We need the detail view to show form for comments and embed the form
functionalities in the same template. NEED it to be a detailview, so we cant
convert it to createview, like we did for the subscribers/home view."""

class PostDetailView(DetailView):
    model = Post

# get context data to use {{comment_form}} in html instead of {{form}}
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comment_form'] = context['form']
        return context

#in the detailview we RENDER the form from our modelform. ONLY RENDER. no functionalities yet
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comment_form'] = CommentModelForm()
        return context

"""the idea is to render form in detailview. after that we make a 'dual' view
Check the comment related views for the next steps"""

#################################################################################

class DraftListView(LoginRequiredMixin,ListView):
    model = Post
    context_object_name = 'draft_list'
    queryset = Post.objects.filter(draft = True)

    #this method is required to be able to make the LIST VIEW choose
    #a template that has a different name than default, "model"_list.html
    def get_template_names(self):
        return ['my_blog/Draft_list.html']

#-----------------------------------------------------------------
#-----------------------------------------------------------------
#-----------------------------------------------------------------

#search funcionality view
class SearchResultsView(ListView):
    model = Post

    #the search is going to return a page structured exactly as the Post_list.html
    template_name = 'my_blog/Post_list.html'

    # this method is required for complex queries in the search bar. Notice, it only has to search posts, NOT drafts
    def get_queryset(self):
        query = self.request.GET.get("q")

        if query is None:
            query = ''

        object_list =  Post.objects.filter(
            Q(post_title__icontains=query) | Q(post_main__icontains=query) | Q(author_f_name__icontains=query) | Q(author_l_name__icontains=query), draft = False
        )
        return object_list

    #we can also return a brand new page by following the code bellow:
    """
    def get_template_names(self):
        return ['my_blog/search_results.html']

    #context data is needed to be able to include the search terms in the template
    # for example when you want the page header to say: "Search results for "SEARCH TERM""

    def get_context_data(self):
        context = super(SearchResultsView, self).get_context_data()
        context['query'] = self.request.GET.get('q') # the term 'q' refers to what is defined as a name in the corresponding html. its a GET request
        return context

    """

#-----------------------------------------------------------------
#-----------------------------------------------------------------
#-----------------------------------------------------------------

#comment related views

"""After we rendered the form in the detailview, create a Formview.
FormView is important to specify which template to use,
the fact that its a POST request(IMPORTANT), and that it makes use of
SingleObjectMixin(IMPORTANT)"""

class CommentCreate(SingleObjectMixin, FormView):
    model = Comment
    form_class = CommentModelForm
    template_name = 'my_blog/Post_detail.html'

    success_url = '#' #by making use of '#' we redirect to the specific post detailview after success

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


"""this is where the magic happens. this is the dual view we planned for.
this view tells us that on a GET request, render the detailview(which renders the form and the blog post).
On POST request (i.e. after form completion and submition),
give the post id its corresponding pk(IMPORTANT), SAVE and use the success url
from the above form(i.e. http://host/post_detail/8/#) """

class PostView(View):

    def get(self, request, *args, **kwargs):
        view = PostDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentCreate.as_view()
        form = CommentModelForm(request.POST) #(IMPORTANT)
        form.instance.post_id = self.kwargs['pk'] #(IMPORTANT)
        if form.is_valid():
            form.save()
        return view(request, *args, **kwargs)


"""THIS (PostView) view we want to use in our urls.py in place of
the simple detailview.
this way we have both rendering and form functionality"""

my_blog/templates/my_blog/Comment_form.html
<form method="post" action="">
    {% csrf_token %}
    {{comment_form.as_p}}
    <input type="submit" value="Submit Comment">
</form>

<!-- possible not needed. CHECK  -->

my_blog/templates/my_blog/Draft_list.html
{% extends "my_blog/home.html" %}
{% load static %}



{% block title %}
<title>Review Drafts</title>
{% endblock %}


{% block content %}
<div class="container text-center">
    <h1 class="text-light"> Update and Publish draft posts</h1>


</div>
<div class="container mt-3 text-center">
    <!--this loop will automatically render new drafts in the list in cards.

    This template also utilizes the image the user provides in the creation (or update), and automatically provides the card image(thumbnail)

    RISK----if user doesnt provide image, there will be an error when trying to render the template
    POSSIBLE FIX-----  Make image input be demanded on creation and update-->

    {% for draft in draft_list %}
        <div class="d-flex flex-column align-items-center">
            <div class="card mb-5 bg-dark text-light border" style="max-width: 85%;" >
                <div class="row g-0">
                    <div class="col-md-4 text-center">
                        <img src="{{draft.post_image.url}}" class="img-fluid rounded-start p-2" alt="...">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title text-success fw-bold">{{draft.post_title}}</h5>
                            <p class="card-text">{{draft.post_main|slice:':300'|safe}}</a></p>
                            <p class="card-text"><small class="text-success">by {{draft.author_f_name}} {{draft.author_l_name}}</small></p>
                            <a href="/update_post/{{draft.id}}" class="btn btn-sm btn-success">Update</a>
                            <a href="/delete_post/{{draft.id}}" class="btn btn-sm btn-success">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    {% endfor %}
</div>








><button onclick="topFunction()" class="btn btn-xs btn-success" id="myBtn" title="Go to top"><img src="{% static '\my_blog\images\up_arrow.png' %}"></button> 


{% endblock %}
<script src="{% static '/my_blog/extra.js' %}"></script>

my_blog/templates/my_blog/Post_detail.html
{% extends 'my_blog/home.html' %}
{% load static %}

{% block title %}
    <title>{{post.post_title}}</title>
{% endblock %}

{% block content %}
<!-- start header -->
<div class="container-fluid text-light" id="PostHeading">
    <h1>{{post.post_title}}:</h1>
    <p class="mx-4">A review by {{post.author_f_name}} {{post.author_l_name}}</p>
    <hr>
</div>
<!-- end header -->


<!-- start post content -->
<div class="container text-light ms-1">
    {{post.post_main|safe}} <!--ALWAYS USE FULL LOWERCASE FOR THE MODEL///USE |safe to display html formatting in the post -->
 
<!-- end post content -->


<!-- begin author card -->
    <h4 class="mx-1 mt-5"><em>About the Author:</em> </h3>
    <div id="AuthorCard" class="card mb-3 mt-3 bg-dark" style="max-width: 540px;">
        
        <div class="row g-0">
            <div class="col-4 col-md-4">
                <img src="{% static '/my_blog/images/blank_profile.jpg' %}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class=" col-8 col-md-8 text-light bg-dark">
                <div class="card-body">
                    <h5 class="card-title">{{post.author_f_name}} {{post.author_l_name}}</h5>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                    <p class="card-text"><small class="text-muted">Author's social media here as a link</small></p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end author card -->


<!-- start comment section -->
<div class="container-fluid text-light m-2 p-2">
    <hr>
    <h3 class="mx-1 mb-3"><u>Comments...</u></h3>
    <!-- comment section should be scrollable separately with overflow-auto and specified height-->
    <div class="col-10 col-sm-10 col-md-8 col-lg-6 col-xl-6 overflow-auto border border-dark border-2" style="height: 25rem;">
        <section style="background-color: #504753;">
        {% for comment in post.comments.all %}
            {% if comment.approved_comment == True %}
            
                <!--start comment card -->
                <div class="row d-flex justify-content-start">
                    <div class="col-12 mb-2 shadow-lg shadow-intensity-lg shadow-danger">
                        <div class="card m-2 border border-rounded border-secondary">
                            <div class="card-body bg-dark">
                                <h6 class="text-success mb-1">
                                    <strong>{{comment.comment_title}}</strong> by <em>{{comment.nickname}}</em>
                                </h6>
                                <p class="text-muted small mb-0">
                                    Shared - {{comment.create_date}}
                                </p>
                                <p class="mt-3 mb-2 pb-2">
                                    {{comment.comment_content}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end comment card -->

            {% endif %}
        {% endfor %} 
    </div>
    <hr>
</div>
<!-- end comment section -->

<div class="container m-2">
    <h4 class="mx-2 mb-4 text-light"><u><em>Leave your comment...</em></u></h4>
    <div class="col-10 col-sm-10 col-md-8 col-lg-6 col-xl-6 ">
            <form method="post">
                {% csrf_token %}
                {% for field in comment_form %}
                <div class="form-floating m-2">
                    {{field}}
                    {{field.label_tag}}
                </div>
                {% endfor %}
               
                <input type="submit" class="btn btn-success m-2 justify-content-center" value="Submit Comment">
            </form>
    </div>
</div>
><button onclick="topFunction()" class="btn btn-xs btn-success" id="myBtn" title="Go to top"><img src="{% static '\my_blog\images\up_arrow.png' %}"></button> 
{% endblock %}

my_blog/templates/my_blog/Post_form.html
{% extends "my_blog/home.html" %}

{% block title %}
    <title>Create Post</title>
{% endblock %}

{% block content %}
<div class="container" id="post_container">
    <form id="postform" method="post" action="" enctype="multipart/form-data"> <!--enctype="multipart/form-data" is used for making the form POST the IMAGE-type thumbnails-->

        {% csrf_token %}
       
            {% for field in form %}

                {% if field.name == 'draft' or field.name == 'post_image' %}
                <div class="form-check col-md-10 col-lg-10 mb-3 ps-0 text-light">
                    {{field.label_tag}}
                    {{field}}
                </div>                
                {% else %}
                <div class="col-md-10 col-lg-10 form-floating mb-3">
                    {{form.media}}<!--make use of ckeditor for rich text field-->
                    {{field}}
                    {{field.label_tag}}
                </div>
                {% endif %}
            {% endfor %}
            
        <input type="submit" class="btn btn-lg btn-success" value="Create Post!">
    </form>
</div>

{% endblock %}

my_blog/templates/my_blog/delete_post_confirm.html
{% extends 'my_blog/home.html' %}

{% block title %}
<title>Delete Post</title>
{% endblock %}

{% block content %}
<div class="container text-center mt-5 mb-5">
    <h4 class="text-light mb-5">Are you sure you want to delete the post titled "<em>{{post.post_title}}</em>" ?</h4>
    <form method="post" action="">
        {% csrf_token %}
        <input type="submit" class="btn btn-lg btn-success" value="Confirm Delete">
    </form>
    <a href="{% url 'my_blog:post_list' %}" class="btn btn-lg btn-success">Go to Posts</a>
</div>
{% endblock %}

my_blog/templates/my_blog/home.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'my_blog/home.css' %}">

    {% block title %}
      <title>Homepage</title>
    {% endblock %}


</head>
<body>
    
  <!-- begin navbar -->

    <nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'my_blog:home' %}">My Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
              {% if user.is_authenticated %}
                <span class = navbar-brand nav-item >Welcome {{user}}!</span>
              {% endif %}
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'my_blog:home' %}">Home</a>
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                  <a class="nav-link active" href="{% url 'logout' %}?next={{request.path}}">Logout</a>
                {% else %}
                  <a class="nav-link active" href="{% url 'login' %}">Login</a>
                {% endif %}
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Posts
                </a>
                
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'my_blog:post_list' %}">View Published Posts</a></li>
                  <li><a class="dropdown-item" href="{% url 'my_blog:draft_list' %}">View Drafts</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'my_blog:create_post' %}">Create Post</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'emails:contact_page' %}">Contact</a>
              </li>
            </ul>
            
            <form class="d-flex justify-content-evenly" method = 'get' action = "{% url 'my_blog:search_results' %}">
              <input class="form-control me-2" name = 'q' type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

  <!-- end navbar -->




<!-- begin main page content -->
{% block content %}
<div class = 'container-fluid text-center text-white mb-3 mt-3'>
  <h1>Welcome to the world of pipe smoking</h1>
</div>

<div class = 'container'>


  <div class = 'row'>

    <div class = 'col'>
      <img src="{% static '/my_blog/images/landing.jpg' %}" class="img-fluid" alt="...">
    </div>
  </div>

  <div class = 'row text-center text-white mb-3 mt-3'>

    <div class = 'col'>
      <h3>Join us on this sensational journey of aromas</h3>
    </div>
    
  </div>


  <div class = 'row align-items-center justify-content-center'>

    <div class = 'col'><img src="{% static '/my_blog/images/im1.jpg' %}" class="img-fluid" alt=""></div>
    <div class = 'col'><img src="{% static '/my_blog/images/im2.jpg' %}" class="img-fluid" alt=""></div>
    <div class = 'col'><img src="{% static '/my_blog/images/im3.jpg' %}" class="img-fluid" alt=""></div>
  </div>
  
</div>


<div class="container mb-3 mt-3">
  <div class = 'row'>
    <h3 class="text-light text-center">If you want to know more, visit our <a href="{% url 'my_blog:post_list' %}"><u>post section</u></a> for reviews!</h3>
  </div>
</div>
<!-- end main page content -->

<!-- begin Subscribe and contact content -->
  <div class="container mb-4 text-light">
    <div class="row border-top border-bottom border-2 border-secondary">
      <div class="col text-center mt-2">
        <div class="row">
          <h4>Whether you're a connoiseur, or just starting your journey:</h4>
        </div>
        <div class="row">
          <h5>Subscribe to be the first to know where the journey will take us.</h5>
        </div>
        <div class="row">
          {% include 'emails/subscriber_form.html' %}
        </div>
      </div>

      <div class="col text-center mt-2">
        <div class="row">
          <h4>Do you have any suggestions and/or feedback?</h4>
        </div>
        <div class="row">
          <h5>We would love to hear from you!</h5>
        </div>
        <div class="row text-center mt-5">
          <div id="contact_btn" class="container">
            <a class="btn btn-lg btn-success" href="{% url 'emails:contact_page' %}"> Contact Us! </a>
          </div>
          <p class="mt-5"><em>We will get back to you as soon as we can.</em></p>
        </div>
      </div>
      
    </div>
    
  </div>
<!-- end subscribe and contact content -->
{% endblock %}



</body>

</html>

my_blog/templates/my_blog/search_results.html
<h1>Search Results for "{{query}}"</h1>
<ul>
    {% for post  in object_list %}
        <li>{{post.post_title}} by {{post.author_l_name}} {{post.author_f_name}}</li>



    {% endfor %}

</ul>